In [2]:
# Importing Libraries
import selenium
import pandas as pd
import time

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

In [4]:
# opening webdriver
driver=webdriver.Chrome(r"//Users/prajwalkunder/Downloads/chromedriver")

### Yatra.comÂ¶

In [5]:
#getting the url
url = "https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=12%2F11%2F2021&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=97063523299&version=1.1&viewName=normal"
driver.get(url)
time.sleep(2)

In [6]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dotted-borderbtm" or @class="cursor-default"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature_time=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="i-b pr"]')
    for i in time:
        depature_time.append(i.text)
except NoSuchElementException:
    depature_time.append('-')
#Arrival time
arrival_time=[]
try:
    time=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
    for i in time:
        arrival_time.append(i.text)
except NoSuchElementException:
    arrival_time.append('-')
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="pr i-b mr-2"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'12/11/2021','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,Air Asia,12/11/2021,New Delhi,Mumbai,20:00,02:25\n+ 1 day,6h 25m,1 Stop,"5,953"
1,Air Asia,12/11/2021,New Delhi,Mumbai,21:25,06:45\n+ 1 day,9h 20m,1 Stop,"5,953"
2,Air Asia,12/11/2021,New Delhi,Mumbai,21:25,07:15\n+ 1 day,9h 50m,1 Stop,"5,953"
3,Air Asia,12/11/2021,New Delhi,Mumbai,20:45,06:45\n+ 1 day,10h 00m,1 Stop,"5,953"
4,Air Asia,12/11/2021,New Delhi,Mumbai,20:45,07:15\n+ 1 day,10h 30m,1 Stop,"5,953"
5,Air Asia,12/11/2021,New Delhi,Mumbai,09:35,20:35,11h 00m,1 Stop,"5,953"
6,Air Asia,12/11/2021,New Delhi,Mumbai,20:00,07:40\n+ 1 day,11h 40m,1 Stop,"5,953"
7,Air Asia,12/11/2021,New Delhi,Mumbai,18:35,06:45\n+ 1 day,12h 10m,1 Stop,"5,953"
8,Air Asia,12/11/2021,New Delhi,Mumbai,08:00,20:35,12h 35m,1 Stop,"5,953"
9,Air Asia,12/11/2021,New Delhi,Mumbai,18:35,07:15\n+ 1 day,12h 40m,1 Stop,"5,953"
10,Go First,12/11/2021,New Delhi,Mumbai,07:00,09:10,2h 10m,Non Stop,"5,954"
11,Go First,12/11/2021,New Delhi,Mumbai,08:00,10:10,2h 10m,Non Stop,"5,954"
12,Go First,12/11/2021,New Delhi,Mumbai,02:00,04:15,2h 15m,Non Stop,"5,954"
13,Go First,12/11/2021,New Delhi,Mumbai,15:00,17:15,2h 15m,Non Stop,"1 left at5,954"
14,Go First,12/11/2021,New Delhi,Mumbai,19:40,21:55,2h 15m,Non Stop,"3 left at5,954"
15,Go First,12/11/2021,New Delhi,Mumbai,21:00,23:15,2h 15m,Non Stop,"3 left at5,954"
16,Go First,12/11/2021,New Delhi,Mumbai,10:30,12:50,2h 20m,Non Stop,"5,954"
17,Go First,12/11/2021,New Delhi,Mumbai,09:00,15:45,6h 45m,1 Stop,"5,954"
18,Go First,12/11/2021,New Delhi,Mumbai,13:45,22:20,8h 35m,2 Stop(s),"5,954"
19,Vistara,12/11/2021,New Delhi,Mumbai,06:00,08:00,2h 00m,Non Stop,"5,955"
20,Air India,12/11/2021,New Delhi,Mumbai,07:00,09:05,2h 05m,Non Stop,"5,955"
21,Vistara,12/11/2021,New Delhi,Mumbai,09:30,11:35,2h 05m,Non Stop,"5,955"
22,SpiceJet,12/11/2021,New Delhi,Mumbai,05:50,08:00,2h 10m,Non Stop,"5,955"
23,IndiGo,12/11/2021,New Delhi,Mumbai,06:30,08:40,2h 10m,Non Stop,"5,955"
24,IndiGo,12/11/2021,New Delhi,Mumbai,07:15,09:25,2h 10m,Non Stop,"5,955"

In [7]:
#getting the url
url = "https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BOM&destinationCountry=IN&flexi=0&flight_depart_date=05%2F11%2F2021&hb=&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1635754693248&viewName=normal"
driver.get(url)

In [8]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dotted-borderbtm" or @class="cursor-default"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature_time=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="i-b pr"]')
    for i in time:
        depature_time.append(i.text)
except NoSuchElementException:
    depature_time.append('-')
#Arrival time
arrival_time=[]
try:
    time=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
    for i in time:
        arrival_time.append(i.text)
except NoSuchElementException:
    arrival_time.append('-')
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="pr i-b mr-2"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df1= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'5/11/2021','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df1

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,Go First,5/11/2021,New Delhi,Mumbai,07:00,09:10,2h 10m,Non Stop,"5,954"
1,Go First,5/11/2021,New Delhi,Mumbai,08:00,10:10,2h 10m,Non Stop,"5,954"
2,Go First,5/11/2021,New Delhi,Mumbai,22:30,00:40\n+ 1 day,2h 10m,Non Stop,"5,954"
3,Go First,5/11/2021,New Delhi,Mumbai,02:00,04:15,2h 15m,Non Stop,"5,954"
4,Go First,5/11/2021,New Delhi,Mumbai,14:20,16:35,2h 15m,Non Stop,"5,954"
5,Go First,5/11/2021,New Delhi,Mumbai,15:00,17:15,2h 15m,Non Stop,"5,954"
6,Go First,5/11/2021,New Delhi,Mumbai,19:40,21:55,2h 15m,Non Stop,"5,954"
7,Go First,5/11/2021,New Delhi,Mumbai,21:00,23:15,2h 15m,Non Stop,"5,954"
8,Go First,5/11/2021,New Delhi,Mumbai,10:30,12:50,2h 20m,Non Stop,"5,954"
9,Go First,5/11/2021,New Delhi,Mumbai,18:05,20:25,2h 20m,Non Stop,"5,954"
10,Go First,5/11/2021,New Delhi,Mumbai,11:30,17:00,5h 30m,1 Stop,"3 left at5,954"
11,Go First,5/11/2021,New Delhi,Mumbai,09:00,15:45,6h 45m,1 Stop,"5,954"
12,Go First,5/11/2021,New Delhi,Mumbai,09:10,16:15,7h 05m,1 Stop,"5,954"
13,Go First,5/11/2021,New Delhi,Mumbai,09:00,17:00,8h 00m,1 Stop,"5,954"
14,Go First,5/11/2021,New Delhi,Mumbai,13:45,22:20,8h 35m,2 Stop(s),"2 left at5,954"
15,Go First,5/11/2021,New Delhi,Mumbai,12:50,22:05,9h 15m,1 Stop,"2 left at5,954"
16,Vistara,5/11/2021,New Delhi,Mumbai,06:00,08:00,2h 00m,Non Stop,"5,955"
17,Air India,5/11/2021,New Delhi,Mumbai,07:00,09:05,2h 05m,Non Stop,"5,955"
18,Vistara,5/11/2021,New Delhi,Mumbai,09:30,11:35,2h 05m,Non Stop,"5,955"
19,IndiGo,5/11/2021,New Delhi,Mumbai,06:30,08:40,2h 10m,Non Stop,"5,955"
20,IndiGo,5/11/2021,New Delhi,Mumbai,07:15,09:25,2h 10m,Non Stop,"5,955"
21,Air India,5/11/2021,New Delhi,Mumbai,08:00,10:10,2h 10m,Non Stop,"5,955"
22,IndiGo,5/11/2021,New Delhi,Mumbai,08:10,10:20,2h 10m,Non Stop,"5,955"
23,Air India,5/11/2021,New Delhi,Mumbai,10:40,12:50,2h 10m,Non Stop,"5,955"
24,IndiGo,5/11/2021,New Delhi,Mumbai,12:00,14:10,2h 10m,Non Stop,"5,955"

In [9]:
#getting the url
url = "https://flight.yatra.com/air-search-ui/dom2/trigger?ADT=1&CHD=0&INF=0&class=Economy&destination=BLR&destinationCountry=IN&flexi=0&flight_depart_date=05%2F11%2F2021&hb=0&noOfSegments=1&origin=DEL&originCountry=IN&type=O&unique=1581283319183&version=1.1&viewName=normal"
driver.get(url)

In [10]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="i-b text ellipsis"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//p[@class="fs-10 font-lightgrey no-wrap city ellipsis"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dotted-borderbtm" or @class="cursor-default"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature_time=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="i-b pr"]')
    for i in time:
        depature_time.append(i.text)
except NoSuchElementException:
    depature_time.append('-')
#Arrival time
arrival_time=[]
try:
    time=driver.find_elements_by_xpath('//p[@class="bold fs-15 mb-2 pr time"]')
    for i in time:
        arrival_time.append(i.text)
except NoSuchElementException:
    arrival_time.append('-')
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//p[@class="fs-12 bold du mb-2"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="pr i-b mr-2"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df2= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'5/11/2021','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df2

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,Air Asia,5/11/2021,New Delhi,Bangalore,16:05,20:40,4h 35m,1 Stop,"7,423"
1,Air Asia,5/11/2021,New Delhi,Bangalore,09:25,14:40,5h 15m,1 Stop,"7,423"
2,Air Asia,5/11/2021,New Delhi,Bangalore,15:25,20:40,5h 15m,1 Stop,"7,423"
3,Air Asia,5/11/2021,New Delhi,Bangalore,05:00,11:35,6h 35m,1 Stop,"7,423"
4,Air Asia,5/11/2021,New Delhi,Bangalore,07:10,13:55,6h 45m,1 Stop,"7,423"
5,Air Asia,5/11/2021,New Delhi,Bangalore,07:10,14:10,7h 00m,1 Stop,"7,423"
6,Air Asia,5/11/2021,New Delhi,Bangalore,09:25,17:00,7h 35m,2 Stop(s),"7,423"
7,Air Asia,5/11/2021,New Delhi,Bangalore,10:05,18:20,8h 15m,1 Stop,"7,423"
8,Air Asia,5/11/2021,New Delhi,Bangalore,20:00,04:15\n+ 1 day,8h 15m,1 Stop,"7,423"
9,Go First,5/11/2021,New Delhi,Bangalore,06:05,08:40,2h 35m,Non Stop,"7,424"
10,Go First,5/11/2021,New Delhi,Bangalore,18:40,21:25,2h 45m,Non Stop,"7,424"
11,Go First,5/11/2021,New Delhi,Bangalore,09:10,13:30,4h 20m,1 Stop,"7,424"
12,Go First,5/11/2021,New Delhi,Bangalore,05:35,10:20,4h 45m,1 Stop,"7,424"
13,Go First,5/11/2021,New Delhi,Bangalore,02:00,07:40,5h 40m,1 Stop,"7,424"
14,Go First,5/11/2021,New Delhi,Bangalore,10:30,16:10,5h 40m,1 Stop,"7,424"
15,Go First,5/11/2021,New Delhi,Bangalore,05:50,12:10,6h 20m,1 Stop,"7,424"
16,Go First,5/11/2021,New Delhi,Bangalore,18:05,00:35\n+ 1 day,6h 30m,1 Stop,"7,424"
17,Go First,5/11/2021,New Delhi,Bangalore,12:45,19:20,6h 35m,1 Stop,"7,424"
18,Go First,5/11/2021,New Delhi,Bangalore,09:00,16:25,7h 25m,1 Stop,"7,424"
19,Go First,5/11/2021,New Delhi,Bangalore,12:45,20:30,7h 45m,1 Stop,"7,424"
20,Go First,5/11/2021,New Delhi,Bangalore,15:00,22:45,7h 45m,1 Stop,"7,424"
21,Go First,5/11/2021,New Delhi,Bangalore,08:00,16:10,8h 10m,1 Stop,"7,424"
22,Go First,5/11/2021,New Delhi,Bangalore,14:20,22:45,8h 25m,1 Stop,"7,424"
23,Go First,5/11/2021,New Delhi,Bangalore,22:30,07:40\n+ 1 day,9h 10m,1 Stop,"3 left at7,424"
24,SpiceJet,5/11/2021,New Delhi,Bangalore,05:35,08:05,2h 30m,Non Stop,"7,425"

### easemytrip.comÂ¶

In [11]:
#getting the url
url = "https://flight.easemytrip.com/FlightList/Index?org=DEL-Delhi,%20India&dept=BLR-Bangalore,%20India&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=5/11/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL="
driver.get(url)

In [12]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="txt-r4 ng-binding"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//span[@class="txt-r3-n ng-binding"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dura_md2 ng-scope"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="txt-r2-n ng-binding"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="dura_md ng-binding"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df3= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'5/11/2021','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df3

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,GO FIRST,5/11/2021,Delhi,Bangalore,06:05,08:40,02h 35m,non-stop,"7,424"
1,SpiceJet,5/11/2021,Delhi,Bangalore,05:35,08:05,02h 30m,non-stop,"7,425"
2,Indigo,5/11/2021,Delhi,Bangalore,06:10,08:50,02h 40m,non-stop,"7,425"
3,Indigo,5/11/2021,Delhi,Bangalore,02:30,05:25,02h 55m,non-stop,"7,425"
4,Indigo,5/11/2021,Delhi,Bangalore,07:20,10:15,02h 55m,non-stop,"7,425"
...,...,...,...,...,...,...,...,...,...
177,Air India,5/11/2021,Delhi,Bangalore,10:15,18:30,08h 15m,2+-stop,"18,884"
178,SpiceJet,5/11/2021,Delhi,Bangalore,11:55,13:35,25h 40m,1-stop,"19,238"
179,Vistara,5/11/2021,Delhi,Bangalore,17:10,18:15,25h 05m,1-stop,"20,235"
180,Air India,5/11/2021,Delhi,Bangalore,20:15,23:20,27h 05m,1-stop,"21,285"
181,Air India,5/11/2021,Delhi,Bangalore,16:45,23:55,07h 10m,1-stop,"34,441"

In [13]:
#getting the url
url = "https://flight.easemytrip.com/FlightList/Index?org=DEL-Delhi,%20India&dept=BLR-Bangalore,%20India&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=4/11/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL="
driver.get(url)

In [14]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="txt-r4 ng-binding"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//span[@class="txt-r3-n ng-binding"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dura_md2 ng-scope"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="txt-r2-n ng-binding"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="dura_md ng-binding"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df4= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'4/11/2021','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df4

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,GO FIRST,4/11/2021,Delhi,Bangalore,06:05,08:40,02h 35m,non-stop,"7,424"
1,SpiceJet,4/11/2021,Delhi,Bangalore,05:35,08:05,02h 30m,non-stop,"7,425"
2,Indigo,4/11/2021,Delhi,Bangalore,06:10,08:50,02h 40m,non-stop,"7,425"
3,SpiceJet,4/11/2021,Delhi,Bangalore,20:10,22:55,02h 45m,non-stop,"7,425"
4,Indigo,4/11/2021,Delhi,Bangalore,07:20,10:15,02h 55m,non-stop,"7,425"
...,...,...,...,...,...,...,...,...,...
139,AirAsia,4/11/2021,Delhi,Bangalore,10:05,18:20,08h 15m,1-stop,"17,138"
140,Vistara,4/11/2021,Delhi,Bangalore,13:20,17:45,28h 25m,2+-stop,"17,182"
141,SpiceJet,4/11/2021,Delhi,Bangalore,13:05,13:00,23h 55m,1-stop,"19,078"
142,SpiceJet,4/11/2021,Delhi,Bangalore,09:25,13:00,27h 35m,1-stop,"19,918"
143,Air India,4/11/2021,Delhi,Bangalore,10:35,23:55,13h 20m,1-stop,"19,951"

In [15]:
#getting the url
url = "https://flight.easemytrip.com/FlightList/Index?org=DEL-Delhi,%20India&dept=BLR-Bangalore,%20India&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=4/12/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL="
driver.get(url)

In [16]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="txt-r4 ng-binding"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//span[@class="txt-r3-n ng-binding"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dura_md2 ng-scope"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="txt-r2-n ng-binding"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="dura_md ng-binding"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df5= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'4/12/2021','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df5

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,SpiceJet,4/12/2021,Delhi,Bangalore,06:15,21:10,14h 55m,1-stop,"3,750"
1,SpiceJet,4/12/2021,Delhi,Bangalore,18:25,21:10,26h 45m,1-stop,"3,960"
2,Air India,4/12/2021,Delhi,Bangalore,06:10,08:55,02h 45m,non-stop,"4,007"
3,Air India,4/12/2021,Delhi,Bangalore,17:20,20:05,02h 45m,non-stop,"4,007"
4,Indigo,4/12/2021,Delhi,Bangalore,06:45,11:50,05h 05m,1-stop,"4,007"
...,...,...,...,...,...,...,...,...,...
199,Vistara,4/12/2021,Delhi,Bangalore,09:40,19:15,09h 35m,1-stop,"13,212"
200,Indigo,4/12/2021,Delhi,Bangalore,17:50,02:35,08h 45m,1-stop,"14,359"
201,Vistara,4/12/2021,Delhi,Bangalore,11:10,16:00,04h 50m,1-stop,"17,925"
202,Air India,4/12/2021,Delhi,Bangalore,18:30,19:50,25h 20m,1-stop,"22,377"
203,GO FIRST,4/12/2021,Delhi,Bangalore,10:45,15:10,04h 25m,1-stop,"23,651"

In [17]:
#getting the url
url = "https://flight.easemytrip.com/FlightList/Index?org=BLR-Bangalore,%20India&dept=BOM-Mumbai,%20India&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=4/12/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL="
driver.get(url)

In [19]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="txt-r4 ng-binding"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//span[@class="txt-r3-n ng-binding"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dura_md2 ng-scope"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="txt-r2-n ng-binding"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="dura_md ng-binding"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df6= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'4/12/2021','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df6

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,GO FIRST,4/12/2021,Kolkata,Mumbai,04:30,07:20,02h 50m,non-stop,"7,958"
1,GO FIRST,4/12/2021,Kolkata,Mumbai,18:30,21:20,02h 50m,non-stop,"7,958"
2,SpiceJet,4/12/2021,Kolkata,Mumbai,22:15,01:05,02h 50m,non-stop,"7,958"
3,Indigo,4/12/2021,Kolkata,Mumbai,19:10,22:10,03h 00m,non-stop,"7,959"
4,Indigo,4/12/2021,Kolkata,Mumbai,17:35,20:40,03h 05m,non-stop,"7,959"
...,...,...,...,...,...,...,...,...,...
104,Vistara,4/12/2021,Kolkata,Mumbai,10:15,20:15,10h 00m,1-stop,"16,400"
105,Vistara,4/12/2021,Kolkata,Mumbai,10:15,20:40,10h 25m,1-stop,"16,400"
106,Vistara,4/12/2021,Kolkata,Mumbai,10:15,18:20,08h 05m,1-stop,"16,794"
107,Vistara,4/12/2021,Kolkata,Mumbai,07:10,18:20,11h 10m,1-stop,"16,794"
108,Vistara,4/12/2021,Kolkata,Mumbai,10:15,22:35,12h 20m,1-stop,"17,240"

In [18]:
#getting the url
url = "https://flight.easemytrip.com/FlightList/Index?org=CCU-Kolkata,%20India&dept=BOM-Mumbai,%20India&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=04/11/2021&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL="
driver.get(url)

In [20]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="txt-r4 ng-binding"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//span[@class="txt-r3-n ng-binding"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dura_md2 ng-scope"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="txt-r2-n ng-binding"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="dura_md ng-binding"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df7= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'4/11/2021','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df7

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,GO FIRST,4/11/2021,Kolkata,Mumbai,04:30,07:20,02h 50m,non-stop,"7,958"
1,GO FIRST,4/11/2021,Kolkata,Mumbai,18:30,21:20,02h 50m,non-stop,"7,958"
2,SpiceJet,4/11/2021,Kolkata,Mumbai,22:15,01:05,02h 50m,non-stop,"7,958"
3,Indigo,4/11/2021,Kolkata,Mumbai,19:10,22:10,03h 00m,non-stop,"7,959"
4,Indigo,4/11/2021,Kolkata,Mumbai,17:35,20:40,03h 05m,non-stop,"7,959"
...,...,...,...,...,...,...,...,...,...
104,Vistara,4/11/2021,Kolkata,Mumbai,10:15,20:15,10h 00m,1-stop,"16,400"
105,Vistara,4/11/2021,Kolkata,Mumbai,10:15,20:40,10h 25m,1-stop,"16,400"
106,Vistara,4/11/2021,Kolkata,Mumbai,10:15,18:20,08h 05m,1-stop,"16,794"
107,Vistara,4/11/2021,Kolkata,Mumbai,07:10,18:20,11h 10m,1-stop,"16,794"
108,Vistara,4/11/2021,Kolkata,Mumbai,10:15,22:35,12h 20m,1-stop,"17,240"

In [21]:
#getting the url
url = "https://flight.easemytrip.com/FlightList/Index?org=CCU-Kolkata,%20India&dept=BOM-Mumbai,%20India&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=04/01/2022&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL="
driver.get(url)

In [22]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="txt-r4 ng-binding"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//span[@class="txt-r3-n ng-binding"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dura_md2 ng-scope"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="txt-r2-n ng-binding"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="dura_md ng-binding"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df8= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'4/01/2022','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df8

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,Indigo,4/01/2022,Kolkata,Mumbai,19:55,05:50,09h 55m,1-stop,"4,120"
1,Air India,4/01/2022,Kolkata,Mumbai,09:40,12:25,02h 45m,non-stop,"4,253"
2,Air India,4/01/2022,Kolkata,Mumbai,16:55,19:45,02h 50m,non-stop,"4,253"
3,Air India,4/01/2022,Kolkata,Mumbai,13:00,16:45,03h 45m,1-stop,"4,253"
4,Indigo,4/01/2022,Kolkata,Mumbai,23:20,05:50,06h 30m,1-stop,"4,287"
...,...,...,...,...,...,...,...,...,...
133,Indigo,4/01/2022,Kolkata,Mumbai,07:30,10:20,02h 50m,non-stop,"11,214"
134,Vistara,4/01/2022,Kolkata,Mumbai,07:10,16:00,08h 50m,1-stop,"12,399"
135,Vistara,4/01/2022,Kolkata,Mumbai,10:15,11:30,25h 15m,1-stop,"12,518"
136,Vistara,4/01/2022,Kolkata,Mumbai,20:20,16:00,19h 40m,1-stop,"12,600"
137,Vistara,4/01/2022,Kolkata,Mumbai,10:15,21:35,11h 20m,1-stop,"13,220"

In [23]:
#getting the url
url = "https://flight.easemytrip.com/FlightList/Index?org=BLR-Bangalore,%20India&dept=BOM-Mumbai,%20India&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=4/02/2022&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL="
driver.get(url)

In [24]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="txt-r4 ng-binding"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//span[@class="txt-r3-n ng-binding"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dura_md2 ng-scope"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="txt-r2-n ng-binding"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="dura_md ng-binding"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df9= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'4/02/2022','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df9

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,GO FIRST,4/02/2022,Bangalore,Mumbai,05:45,07:20,01h 35m,non-stop,"2,202"
1,Indigo,4/02/2022,Bangalore,Mumbai,04:30,06:10,01h 40m,non-stop,"2,202"
2,AirAsia,4/02/2022,Bangalore,Mumbai,05:35,07:15,01h 40m,non-stop,"2,202"
3,GO FIRST,4/02/2022,Bangalore,Mumbai,08:10,09:50,01h 40m,non-stop,"2,202"
4,AirAsia,4/02/2022,Bangalore,Mumbai,18:50,20:35,01h 45m,non-stop,"2,202"
...,...,...,...,...,...,...,...,...,...
182,Vistara,4/02/2022,Bangalore,Mumbai,11:30,20:05,08h 35m,1-stop,"10,039"
183,Vistara,4/02/2022,Bangalore,Mumbai,11:30,21:15,09h 45m,1-stop,"10,039"
184,Vistara,4/02/2022,Bangalore,Mumbai,11:30,22:00,10h 30m,1-stop,"10,039"
185,Vistara,4/02/2022,Bangalore,Mumbai,18:50,08:00,13h 10m,1-stop,"11,205"
186,Vistara,4/02/2022,Bangalore,Mumbai,18:50,09:45,14h 55m,1-stop,"11,205"

In [25]:
#getting the url
url = "https://flight.easemytrip.com/FlightList/Index?org=BLR-Bangalore,%20India&dept=MAA-Chennai,%20India&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=4/02/2022&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL="
driver.get(url)

In [26]:

#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="txt-r4 ng-binding"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//span[@class="txt-r3-n ng-binding"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dura_md2 ng-scope"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="txt-r2-n ng-binding"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="dura_md ng-binding"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df10= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'4/02/2022','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df10

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,AirAsia,4/02/2022,Bangalore,Chennai,15:35,16:30,00h 55m,non-stop,"1,604"
1,AirAsia,4/02/2022,Bangalore,Chennai,07:30,08:30,01h 00m,non-stop,"1,604"
2,AirAsia,4/02/2022,Bangalore,Chennai,16:15,17:25,01h 10m,non-stop,"1,604"
3,Indigo,4/02/2022,Bangalore,Chennai,18:15,19:15,01h 00m,non-stop,"1,606"
4,Indigo,4/02/2022,Bangalore,Chennai,10:55,12:00,01h 05m,non-stop,"1,606"
...,...,...,...,...,...,...,...,...,...
90,Vistara,4/02/2022,Bangalore,Chennai,11:30,23:05,11h 35m,2+-stop,"15,604"
91,Vistara,4/02/2022,Bangalore,Chennai,06:40,16:20,09h 40m,1-stop,"15,930"
92,Vistara,4/02/2022,Bangalore,Chennai,09:30,20:15,10h 45m,1-stop,"15,930"
93,Vistara,4/02/2022,Bangalore,Chennai,11:30,22:45,11h 15m,1-stop,"15,930"
94,Vistara,4/02/2022,Bangalore,Chennai,11:30,22:45,11h 15m,1-stop,"15,930"

In [27]:
#getting the url
url = "https://flight.easemytrip.com/FlightList/Index?org=BLR-Bangalore,%20India&dept=MAA-Chennai,%20India&adt=1&chd=0&inf=0&cabin=0&airline=Any&deptDT=01/02/2022&arrDT=&isOneway=true&isDomestic=true&CouponCode=&lang=&ompAff=&bc=&ISWL="
driver.get(url)

In [28]:

#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//span[@class="txt-r4 ng-binding"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//span[@class="txt-r3-n ng-binding"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="dura_md2 ng-scope"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="txt-r2-n ng-binding"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//span[@class="dura_md ng-binding"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//div[@class="col-md-8 col-sm-8 col-xs-9 txt-r6-n ng-binding"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df11= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'4/01/2022','Source':Source,'Destination':destination,'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df11

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,AirAsia,4/01/2022,Bangalore,Chennai,12:50,13:45,00h 55m,non-stop,"1,604"
1,AirAsia,4/01/2022,Bangalore,Chennai,15:35,16:30,00h 55m,non-stop,"1,604"
2,AirAsia,4/01/2022,Bangalore,Chennai,07:30,08:30,01h 00m,non-stop,"1,604"
3,AirAsia,4/01/2022,Bangalore,Chennai,16:15,17:25,01h 10m,non-stop,"1,604"
4,Indigo,4/01/2022,Bangalore,Chennai,22:55,23:45,00h 50m,non-stop,"1,606"
...,...,...,...,...,...,...,...,...,...
89,Vistara,4/01/2022,Bangalore,Chennai,11:30,23:05,11h 35m,2+-stop,"15,499"
90,Vistara,4/01/2022,Bangalore,Chennai,06:40,16:20,09h 40m,1-stop,"15,930"
91,Vistara,4/01/2022,Bangalore,Chennai,09:30,20:15,10h 45m,1-stop,"15,930"
92,Vistara,4/01/2022,Bangalore,Chennai,11:30,22:45,11h 15m,1-stop,"15,930"
93,Vistara,4/01/2022,Bangalore,Chennai,11:30,22:45,11h 15m,1-stop,"15,930"

### via.com

In [44]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=BLR&bdestination=BLR&destinationL=Bangalore&destinationCity=&destinationCN=&source=HYD&bsource=HYD&sourceL=Hyderabad&sourceCity=&sourceCN=&month=11&day=4&year=2021&date=11/4/2021&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=INTL&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [47]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df12= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'4/11/2021','Source':Source[:74],'Destination':destination[:74],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df12

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,Star Air,4/11/2021,HYD Hyderabad,BLR Bangalore,20:20,21:25,1h 5m Non-Stop,Non-Stop,"4,452"
1,AirIndia,4/11/2021,Hyderabad,Bangalore,09:20,10:25,1h 5m Non-Stop,Non-Stop,"4,453"
2,IndiGo,4/11/2021,Hyderabad,Bangalore,19:40,20:45,1h 5m Non-Stop,Non-Stop,"4,453"
3,IndiGo,4/11/2021,Hyderabad,Bangalore,09:30,10:45,1h 15m Non-Stop,Non-Stop,"4,453"
4,IndiGo,4/11/2021,Hyderabad,Bangalore,21:35,22:50,1h 15m Non-Stop,Non-Stop,"4,453"
...,...,...,...,...,...,...,...,...,...
69,GO FIRST,4/11/2021,Hyderabad,Bangalore,06:05,19:20,13h 15m 1 Stop(s),1 Stop(s),"13,905"
70,AirIndia,4/11/2021,Hyderabad,Bangalore,08:25,11:10,26h 45m 1 Stop(s),1 Stop(s),"20,974"
71,AirIndia,4/11/2021,Hyderabad,Bangalore,06:00,16:45,10h 45m 1 Stop(s),1 Stop(s),"25,936"
72,AirIndia,4/11/2021,Hyderabad,Bangalore,11:15,20:05,8h 50m 1 Stop(s),1 Stop(s),"27,682"
73,AirIndia,4/11/2021,Hyderabad,Bangalore,11:15,23:55,12h 40m 1 Stop(s),1 Stop(s),"27,682"

In [42]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=BLR&bdestination=BLR&destinationL=Bangalore&destinationCity=&destinationCN=&source=HYD&bsource=HYD&sourceL=Hyderabad&sourceCity=&sourceCN=&month=12&day=8&year=2021&date=12/8/2021&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=INTL&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [43]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df13= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'8/12/2021','Source':Source[:120],'Destination':destination[:120],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df13

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,GO FIRST,8/12/2021,HYD Hyderabad,BLR Bangalore,05:15,06:15,1h 0m Non-Stop,Non-Stop,"1,802"
1,AirAsia India,8/12/2021,Hyderabad,Bangalore,22:10,23:10,1h 0m Non-Stop,Non-Stop,"1,802"
2,AirAsia India,8/12/2021,Hyderabad,Bangalore,00:45,01:55,1h 10m Non-Stop,Non-Stop,"1,802"
3,AirAsia India,8/12/2021,Hyderabad,Bangalore,14:20,15:30,1h 10m Non-Stop,Non-Stop,"1,802"
4,AirAsia India,8/12/2021,Hyderabad,Bangalore,19:45,20:55,1h 10m Non-Stop,Non-Stop,"1,802"
...,...,...,...,...,...,...,...,...,...
115,AirIndia,8/12/2021,Hyderabad,Bangalore,16:15,11:10,18h 55m 2 Stop(s),2 Stop(s),"8,713"
116,GO FIRST,8/12/2021,Hyderabad,Bangalore,09:00,14:55,5h 55m 1 Stop(s),1 Stop(s),"9,038"
117,Vistara,8/12/2021,Hyderabad,Bangalore,20:35,11:50,15h 15m 1 Stop(s),1 Stop(s),"10,483"
118,Vistara,8/12/2021,Hyderabad,Bangalore,17:40,11:50,18h 10m 1 Stop(s),1 Stop(s),"10,483"
119,GO FIRST,8/12/2021,Hyderabad,Bangalore,19:30,07:45,12h 15m 1 Stop(s),1 Stop(s),"13,086"

In [48]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=BOM&bdestination=BOM&destinationL=Mumbai,Mumbai&destinationCity=Mumbai&destinationCN=India&source=BLR&bsource=BLR&sourceL=Bangalore,Bangalore&sourceCity=Bangalore&sourceCN=India&month=11&day=11&year=2021&date=11/11/2021&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=DOM&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [51]:

#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df14= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'11/11/2021','Source':Source[:151],'Destination':destination[:151],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df14

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,GO FIRST,11/11/2021,BLR Bangalore,BOM Mumbai,05:45,07:20,1h 35m Non-Stop,Non-Stop,"2,824"
1,GO FIRST,11/11/2021,Bangalore,Mumbai,08:10,09:50,1h 40m Non-Stop,Non-Stop,"2,824"
2,GO FIRST,11/11/2021,Bangalore,Mumbai,22:00,23:55,1h 55m Non-Stop,Non-Stop,"3,422"
3,AirAsia India,11/11/2021,Bangalore,Mumbai,20:45,02:25,5h 40m 1 Stop(s),1 Stop(s),"5,176"
4,AirAsia India,11/11/2021,Bangalore,Mumbai,22:10,06:35,8h 25m 1 Stop(s),1 Stop(s),"5,176"
...,...,...,...,...,...,...,...,...,...
146,GO FIRST,11/11/2021,Bangalore,Mumbai,06:30,12:30,6h 0m 1 Stop(s),1 Stop(s),"13,604"
147,AirIndia,11/11/2021,Bangalore,Mumbai,09:00,22:25,13h 25m 2 Stop(s),2 Stop(s),"14,472"
148,GO FIRST,11/11/2021,Bangalore,Mumbai,07:40,17:15,9h 35m 1 Stop(s),1 Stop(s),"14,743"
149,GO FIRST,11/11/2021,Bangalore,Mumbai,07:40,16:35,8h 55m 1 Stop(s),1 Stop(s),"15,340"
150,AirIndia,11/11/2021,Bangalore,Mumbai,17:45,16:45,23h 0m 1 Stop(s),1 Stop(s),"33,665"

In [52]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=BLR&bdestination=BLR&destinationL=Bangalore,Bangalore&destinationCity=Bangalore&destinationCN=India&source=DEL&bsource=DEL&sourceL=Delhi,Delhi&sourceCity=Delhi&sourceCN=India&month=12&day=8&year=2021&date=12/8/2021&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=DOM&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [55]:

#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df15= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'8/12/2021','Source':Source[:150],'Destination':destination[:150],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df15

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,SpiceJet,8/12/2021,DEL Delhi,BLR Bangalore,06:15,21:10,14h 55m 1 Stop(s),1 Stop(s),"3,750"
1,SpiceJet,8/12/2021,Delhi,Bangalore,18:25,21:10,26h 45m 1 Stop(s),1 Stop(s),"3,750"
2,IndiGo,8/12/2021,Delhi,Bangalore,08:25,15:40,7h 15m 1 Stop(s),1 Stop(s),"3,753"
3,AirIndia,8/12/2021,Delhi,Bangalore,06:10,08:55,2h 45m Non-Stop,Non-Stop,"4,007"
4,AirIndia,8/12/2021,Delhi,Bangalore,09:45,12:30,2h 45m Non-Stop,Non-Stop,"4,007"
...,...,...,...,...,...,...,...,...,...
145,GO FIRST,8/12/2021,Delhi,Bangalore,10:45,17:10,6h 25m 1 Stop(s),1 Stop(s),"7,649"
146,SpiceJet,8/12/2021,Delhi,Bangalore,11:55,13:35,25h 40m 1 Stop(s),1 Stop(s),"7,708"
147,AirIndia,8/12/2021,Delhi,Bangalore,11:00,17:05,6h 5m 1 Stop(s),1 Stop(s),"7,727"
148,AirIndia,8/12/2021,Delhi,Bangalore,14:10,01:20,11h 10m 1 Stop(s),1 Stop(s),"7,761"
149,SpiceJet,8/12/2021,Delhi,Bangalore,13:05,12:50,23h 45m 1 Stop(s),1 Stop(s),"7,820"

In [56]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=BOM&bdestination=BOM&destinationL=Mumbai,Mumbai&destinationCity=Mumbai&destinationCN=India&source=DEL&bsource=DEL&sourceL=Delhi,Delhi&sourceCity=Delhi&sourceCN=India&month=3&day=9&year=2022&date=3/9/2022&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=DOM&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [59]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df16= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'09/03/2022','Source':Source[:189],'Destination':destination[:189],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df16

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,IndiGo,09/03/2022,DEL Delhi,BOM Mumbai,02:30,04:40,2h 10m Non-Stop,Non-Stop,"2,456"
1,AirAsia India,09/03/2022,Delhi,Mumbai,04:25,06:35,2h 10m Non-Stop,Non-Stop,"2,456"
2,GO FIRST,09/03/2022,Delhi,Mumbai,07:00,09:10,2h 10m Non-Stop,Non-Stop,"2,456"
3,GO FIRST,09/03/2022,Delhi,Mumbai,08:00,10:10,2h 10m Non-Stop,Non-Stop,"2,456"
4,GO FIRST,09/03/2022,Delhi,Mumbai,02:00,04:15,2h 15m Non-Stop,Non-Stop,"2,456"
...,...,...,...,...,...,...,...,...,...
184,Vistara,09/03/2022,Delhi,Mumbai,17:35,11:25,17h 50m 1 Stop(s),1 Stop(s),"9,005"
185,Vistara,09/03/2022,Delhi,Mumbai,17:35,13:15,19h 40m 1 Stop(s),1 Stop(s),"9,005"
186,Vistara,09/03/2022,Delhi,Mumbai,19:50,20:15,24h 25m 1 Stop(s),1 Stop(s),"9,005"
187,Vistara,09/03/2022,Delhi,Mumbai,19:50,21:50,26h 0m 1 Stop(s),1 Stop(s),"9,005"
188,Vistara,09/03/2022,Delhi,Mumbai,17:35,20:15,26h 40m 1 Stop(s),1 Stop(s),"9,005"

In [60]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=BOM&bdestination=BOM&destinationL=Mumbai&destinationCity=&destinationCN=&source=HYD&bsource=HYD&sourceL=Hyderabad,Hyderabad&sourceCity=Hyderabad&sourceCN=India&month=3&day=9&year=2022&date=3/9/2022&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=DOM&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [61]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df17= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'09/03/2022','Source':Source[:123],'Destination':destination[:123],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df17

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,AirIndia,09/03/2022,HYD Hyderabad,BOM Mumbai,22:15,23:55,1h 40m Non-Stop,Non-Stop,"2,301"
1,IndiGo,09/03/2022,Hyderabad,Mumbai,13:50,21:45,7h 55m 1 Stop(s),1 Stop(s),"2,301"
2,IndiGo,09/03/2022,Hyderabad,Mumbai,17:50,19:40,1h 50m Non-Stop,Non-Stop,"2,305"
3,IndiGo,09/03/2022,Hyderabad,Mumbai,20:15,22:05,1h 50m Non-Stop,Non-Stop,"2,305"
4,IndiGo,09/03/2022,Hyderabad,Mumbai,22:00,23:50,1h 50m Non-Stop,Non-Stop,"2,305"
...,...,...,...,...,...,...,...,...,...
118,Vistara,09/03/2022,Hyderabad,Mumbai,20:35,17:40,21h 5m 1 Stop(s),1 Stop(s),"10,784"
119,Vistara,09/03/2022,Hyderabad,Mumbai,17:40,15:00,21h 20m 1 Stop(s),1 Stop(s),"10,784"
120,Vistara,09/03/2022,Hyderabad,Mumbai,10:05,08:00,21h 55m 1 Stop(s),1 Stop(s),"10,784"
121,Vistara,09/03/2022,Hyderabad,Mumbai,20:35,19:05,22h 30m 1 Stop(s),1 Stop(s),"10,784"
122,Vistara,09/03/2022,Hyderabad,Mumbai,17:40,16:30,22h 50m 1 Stop(s),1 Stop(s),"10,784"

In [62]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=BOM&bdestination=BOM&destinationL=Mumbai&destinationCity=&destinationCN=&source=HYD&bsource=HYD&sourceL=Hyderabad&sourceCity=&sourceCN=&month=11&day=9&year=2021&date=11/9/2021&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=INTL&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [65]:

#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df18= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'09/11/2021','Source':Source[:125],'Destination':destination[:125],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df18

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,AirAsia India,09/11/2021,HYD Hyderabad,BOM Mumbai,00:45,06:45,6h 0m 1 Stop(s),1 Stop(s),"4,451"
1,AirAsia India,09/11/2021,Hyderabad,Mumbai,14:20,20:35,6h 15m 1 Stop(s),1 Stop(s),"4,451"
2,AirAsia India,09/11/2021,Hyderabad,Mumbai,00:45,07:15,6h 30m 1 Stop(s),1 Stop(s),"4,451"
3,AirAsia India,09/11/2021,Hyderabad,Mumbai,22:10,06:45,8h 35m 1 Stop(s),1 Stop(s),"4,451"
4,AirAsia India,09/11/2021,Hyderabad,Mumbai,22:10,07:15,9h 5m 1 Stop(s),1 Stop(s),"4,451"
...,...,...,...,...,...,...,...,...,...
120,IndiGo,09/11/2021,Hyderabad,Mumbai,05:40,14:25,8h 45m 1 Stop(s),1 Stop(s),"13,641"
121,AirIndia,09/11/2021,Hyderabad,Mumbai,06:25,17:05,10h 40m 1 Stop(s),1 Stop(s),"16,633"
122,AirIndia,09/11/2021,Hyderabad,Mumbai,06:00,12:25,6h 25m 1 Stop(s),1 Stop(s),"18,313"
123,AirIndia,09/11/2021,Hyderabad,Mumbai,06:00,19:45,13h 45m 1 Stop(s),1 Stop(s),"18,313"
124,AirIndia,09/11/2021,Hyderabad,Mumbai,13:05,19:45,6h 40m 2 Stop(s),2 Stop(s),"21,463"

In [66]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=BOM&bdestination=BOM&destinationL=Mumbai&destinationCity=&destinationCN=&source=HYD&bsource=HYD&sourceL=Hyderabad&sourceCity=&sourceCN=&month=12&day=9&year=2021&date=12/9/2021&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=INTL&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [69]:

#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df19= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'09/12/2021','Source':Source[:129],'Destination':destination[:129],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df19

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,AirIndia,09/12/2021,HYD Hyderabad,BOM Mumbai,08:25,09:40,1h 15m Non-Stop,Non-Stop,"2,301"
1,IndiGo,09/12/2021,Hyderabad,Mumbai,15:10,19:55,4h 45m 1 Stop(s),1 Stop(s),"2,301"
2,IndiGo,09/12/2021,Hyderabad,Mumbai,04:30,05:50,1h 20m Non-Stop,Non-Stop,"2,305"
3,IndiGo,09/12/2021,Hyderabad,Mumbai,06:15,07:45,1h 30m Non-Stop,Non-Stop,"2,305"
4,IndiGo,09/12/2021,Hyderabad,Mumbai,10:45,12:15,1h 30m Non-Stop,Non-Stop,"2,305"
...,...,...,...,...,...,...,...,...,...
124,AirIndia,09/12/2021,Hyderabad,Mumbai,06:00,19:45,13h 45m 1 Stop(s),1 Stop(s),"7,175"
125,GO FIRST,09/12/2021,Hyderabad,Mumbai,09:00,17:00,8h 0m 1 Stop(s),1 Stop(s),"7,915"
126,AirAsia India,09/12/2021,Hyderabad,Mumbai,16:10,02:25,10h 15m 1 Stop(s),1 Stop(s),"8,237"
127,AirAsia India,09/12/2021,Hyderabad,Mumbai,16:10,02:25,10h 15m 1 Stop(s),1 Stop(s),"8,761"
128,IndiGo,09/12/2021,Hyderabad,Mumbai,05:40,14:25,8h 45m 1 Stop(s),1 Stop(s),"11,371"

In [70]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=COK&bdestination=COK&destinationL=Cochin,Cochin&destinationCity=Cochin&destinationCN=India&source=PNQ&bsource=PNQ&sourceL=Pune,Pune&sourceCity=Pune&sourceCN=India&month=12&day=15&year=2021&date=12/15/2021&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=DOM&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [73]:

#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df20= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'15/12/2021','Source':Source[:215],'Destination':destination[:215],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df20

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,IndiGo,15/12/2021,PNQ Pune,COK Cochin,22:20,07:00,8h 40m 1 Stop(s),1 Stop(s),"3,376"
1,IndiGo,15/12/2021,Pune,Cochin,23:55,09:30,9h 35m 1 Stop(s),1 Stop(s),"3,376"
2,AirAsia India,15/12/2021,Pune,Cochin,19:25,22:20,2h 55m 1 Stop(s),1 Stop(s),"3,437"
3,IndiGo,15/12/2021,Pune,Cochin,13:55,20:50,6h 55m 1 Stop(s),1 Stop(s),"3,765"
4,IndiGo,15/12/2021,Pune,Cochin,13:55,22:35,8h 40m 1 Stop(s),1 Stop(s),"3,765"
...,...,...,...,...,...,...,...,...,...
210,Multiple Airlines,15/12/2021,Pune,Cochin,01:00,19:10,18h 10m 2 Stop(s),2 Stop(s),"12,845"
211,Multiple Airlines,15/12/2021,Pune,Cochin,07:20,09:05,25h 45m 2 Stop(s),2 Stop(s),"13,125"
212,Multiple Airlines,15/12/2021,Pune,Cochin,01:00,17:20,16h 20m 2 Stop(s),2 Stop(s),"15,353"
213,Multiple Airlines,15/12/2021,Pune,Cochin,04:50,17:20,12h 30m 2 Stop(s),2 Stop(s),"15,773"
214,Multiple Airlines,15/12/2021,Pune,Cochin,01:00,17:20,16h 20m 2 Stop(s),2 Stop(s),"15,773"

In [77]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=COK&bdestination=COK&destinationL=Cochin&destinationCity=&destinationCN=&source=PNQ&bsource=PNQ&sourceL=Pune&sourceCity=&sourceCN=&month=11&day=18&year=2021&date=11/18/2021&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=INTL&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [80]:

#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df21= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'18/11/2021','Source':Source[:138],'Destination':destination[:138],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df21

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,AirAsia India,18/11/2021,PNQ Pune,COK Cochin,19:25,22:20,2h 55m 1 Stop(s),1 Stop(s),"5,430"
1,AirAsia India,18/11/2021,Pune,Cochin,19:25,07:00,11h 35m 1 Stop(s),1 Stop(s),"5,431"
2,IndiGo,18/11/2021,Pune,Cochin,09:45,11:25,1h 40m Non-Stop,Non-Stop,"5,433"
3,IndiGo,18/11/2021,Pune,Cochin,08:10,13:35,5h 25m 1 Stop(s),1 Stop(s),"5,433"
4,IndiGo,18/11/2021,Pune,Cochin,14:40,22:10,7h 30m 1 Stop(s),1 Stop(s),"5,433"
...,...,...,...,...,...,...,...,...,...
133,Multiple Airlines,18/11/2021,Pune,Cochin,09:10,09:05,23h 55m 2 Stop(s),2 Stop(s),"19,317"
134,Multiple Airlines,18/11/2021,Pune,Cochin,09:10,09:05,23h 55m 2 Stop(s),2 Stop(s),"19,317"
135,Multiple Airlines,18/11/2021,Pune,Cochin,09:10,09:05,23h 55m 2 Stop(s),2 Stop(s),"19,317"
136,Multiple Airlines,18/11/2021,Pune,Cochin,15:05,17:20,26h 15m 2 Stop(s),2 Stop(s),"21,383"
137,Multiple Airlines,18/11/2021,Pune,Cochin,14:45,17:20,26h 35m 2 Stop(s),2 Stop(s),"21,383"

In [81]:
#getting the url
url = "https://in.via.com/flight/search?returnType=one-way&destination=BLR&bdestination=BLR&destinationL=Bangalore,Bangalore&destinationCity=Bangalore&destinationCN=India&source=COK&bsource=COK&sourceL=Cochin,Cochin&sourceCity=Cochin&sourceCN=India&month=12&day=22&year=2021&date=12/22/2021&numAdults=1&numChildren=0&numInfants=0&validation_result=&domesinter=international&livequote=-1&flightClass=ALL&travType=DOM&routingType=ALL&preferredCarrier=&prefCarrier=0&isAjax=false"
driver.get(url)

In [84]:
#Airline details
airline_name=[]  
try:
    name=driver.find_elements_by_xpath('//div[@class="name js-toolTip"]')
    for i in name:
        airline_name.append(i.text)
except NoSuchElementException:
    airline_name.append('-')
#place
source=[]
try:
    Source=driver.find_elements_by_xpath('//div[@class="city"]')
    for i in Source:
        source.append(i.text)
except NoSuchElementException:
    source.append('-')
    
#Source  
Source=[]
for i in range(0,len(source)-1,2):
    Source.append(source[i])
#destination
destination=[]
for i in range(0,len(source)-1,2):
    destination.append(source[i+1])
    
# total stops
stops=[]
try:
    stop=driver.find_elements_by_xpath('//span[@class="stops"]')
    for i in stop:
        stops.append(i.text)
except NoSuchElementException:
    stops.append('-')
#departure time 
depature=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="time"]')
    for i in time:
        depature.append(i.text)
except NoSuchElementException:
    depature.append('-')
    
#destination
depature_time=[]
arrival_time=[]
for i in range(0,len(depature)-1,2):
    depature_time.append(depature[i])
    arrival_time.append(depature[i+1])
    
    
#duration
duration=[]
try:
    time=driver.find_elements_by_xpath('//div[@class="dur"]')
    for i in time:
        duration.append(i.text)
except NoSuchElementException:
    duration.append('-')
    
#fare
price=[]
try:
    fare=driver.find_elements_by_xpath('//span[@class="price"]')
    for i in fare:
        price.append(i.text)
except NoSuchElementException:
    price.append('-')
#Making dataframe
# creating a pandas dataframe
df22= pd.DataFrame({'airline_name':airline_name,'date_of_journey':'22/12/2021','Source':Source[:286],'Destination':destination[:286],'depature_time':depature_time,'arrival_time':arrival_time,'duration':duration,'total_stops':stops,'Price':price})
  # show the dataframe
df22

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,AirAsia India,22/12/2021,COK Cochin,BLR Bangalore,21:25,22:25,1h 0m Non-Stop,Non-Stop,"2,049"
1,IndiGo,22/12/2021,Cochin,Bangalore,22:00,23:00,1h 0m Non-Stop,Non-Stop,"2,049"
2,IndiGo,22/12/2021,Cochin,Bangalore,11:25,12:30,1h 5m Non-Stop,Non-Stop,"2,049"
3,AirAsia India,22/12/2021,Cochin,Bangalore,14:45,15:50,1h 5m Non-Stop,Non-Stop,"2,049"
4,IndiGo,22/12/2021,Cochin,Bangalore,07:30,08:45,1h 15m Non-Stop,Non-Stop,"2,049"
...,...,...,...,...,...,...,...,...,...
281,Multiple Airlines,22/12/2021,Cochin,Bangalore,00:25,14:45,14h 20m 3 Stop(s),3 Stop(s),"16,624"
282,Multiple Airlines,22/12/2021,Cochin,Bangalore,00:25,22:15,21h 50m 2 Stop(s),2 Stop(s),"16,624"
283,Multiple Airlines,22/12/2021,Cochin,Bangalore,00:25,15:30,15h 5m 2 Stop(s),2 Stop(s),"16,651"
284,Multiple Airlines,22/12/2021,Cochin,Bangalore,00:25,20:55,20h 30m 2 Stop(s),2 Stop(s),"16,651"
285,Multiple Airlines,22/12/2021,Cochin,Bangalore,00:25,23:10,22h 45m 2 Stop(s),2 Stop(s),"16,651"

In [83]:
len(airline_name),len(Source),len(destination),len(stops),len(depature_time),len(arrival_time),len(duration),len(price)

(286, 288, 288, 286, 286, 286, 286, 286)

## concatinating the dataframes

In [85]:
data=pd.concat([df,df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22],ignore_index=True)

In [86]:
data

,airline_name,date_of_journey,Source,Destination,depature_time,arrival_time,duration,total_stops,Price
0,Air Asia,12/11/2021,New Delhi,Mumbai,20:00,02:25\n+ 1 day,6h 25m,1 Stop,"5,953"
1,Air Asia,12/11/2021,New Delhi,Mumbai,21:25,06:45\n+ 1 day,9h 20m,1 Stop,"5,953"
2,Air Asia,12/11/2021,New Delhi,Mumbai,21:25,07:15\n+ 1 day,9h 50m,1 Stop,"5,953"
3,Air Asia,12/11/2021,New Delhi,Mumbai,20:45,06:45\n+ 1 day,10h 00m,1 Stop,"5,953"
4,Air Asia,12/11/2021,New Delhi,Mumbai,20:45,07:15\n+ 1 day,10h 30m,1 Stop,"5,953"
...,...,...,...,...,...,...,...,...,...
3032,Multiple Airlines,22/12/2021,Cochin,Bangalore,00:25,14:45,14h 20m 3 Stop(s),3 Stop(s),"16,624"
3033,Multiple Airlines,22/12/2021,Cochin,Bangalore,00:25,22:15,21h 50m 2 Stop(s),2 Stop(s),"16,624"
3034,Multiple Airlines,22/12/2021,Cochin,Bangalore,00:25,15:30,15h 5m 2 Stop(s),2 Stop(s),"16,651"
3035,Multiple Airlines,22/12/2021,Cochin,Bangalore,00:25,20:55,20h 30m 2 Stop(s),2 Stop(s),"16,651"
3036,Multiple Airlines,22/12/2021,Cochin,Bangalore,00:25,23:10,22h 45m 2 Stop(s),2 Stop(s),"16,651"

### Saving into execl file

In [87]:
# writing to Excel
datatoexcel = pd.ExcelWriter('flight_price_prediction.xlsx')
  
# write DataFrame to excel
data.to_excel(datatoexcel)
  
# save to excel
datatoexcel.save()